version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - OPENVPN_USER=${PROTON_DEFAULTUSER_NAME}
      - OPENVPN_PASSWORD=${PROTON_DEFAULTUSER_PASS}
      - SERVER_COUNTRIES=${PROTON_COUNTRY}